import os
import numpy as np
import pandas as pd
from scipy.signal import butter, filtfilt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import joblib

# ==========================================
# 1. DSP & PARSING FUNCTIONS
# ==========================================

def parse_all_subcarriers(filepath):
    """Reads the pre-calculated amplitude CSV directly."""
    if not os.path.exists(filepath):
        print(f"❌ ERROR: File not found: {filepath}")
        return None
    # Read the clean CSV generated by your new csi_logger.py
    df = pd.read_csv(filepath)
    return df.values

def apply_dsp_pipeline(data, fs=100):
    """Applies Background Subtraction and Butterworth Filter."""
    df = pd.DataFrame(data)
    rolling_mean = df.rolling(window=100, min_periods=1).mean()
    dyn_data = (df - rolling_mean).values
    
    nyq = 0.5 * fs
    b, a = butter(3, [0.1/nyq, 3.0/nyq], btype='band')
    if dyn_data.shape[0] < 15: return dyn_data
    return filtfilt(b, a, dyn_data, axis=0)

# ==========================================
# 2. FEATURE EXTRACTION (The "Fingerprint")
# ==========================================

def extract_features(filtered_data, label, window_size=100, step_size=20):
    """Chops data into blocks. Step_size 20 limits overfitting."""
    features = []
    labels = []
    for i in range(0, len(filtered_data) - window_size, step_size):
        window = filtered_data[i:i + window_size]
        variance_vector = np.var(window, axis=0) 
        features.append(variance_vector)
        labels.append(label)
    return features, labels

# ==========================================
# 3. MAIN MACHINE LEARNING PIPELINE
# ==========================================

if __name__ == "__main__":
    print("🚀 Booting PRISM AI (Full Zonal Localization)...")

    # Route to your data folder
    DATA_DIR = os.path.expanduser('~/sem6/RF/wifi_localization/data')

    # Define files and labels
    dataset_files = {
        "empty_room.csv": 0,       
        "zone_a.csv": 1,       
        "zone_b.csv": 2,           
        "zone_c.csv": 3            
    }

    class_names = ["Empty Room", "Zone A (Table)", "Zone B (Middle)", "Zone C (Door)"]

    all_features = []
    all_labels = []

    # 1. Load and Process all files from the data directory
    for filename, label in dataset_files.items():
        full_path = os.path.join(DATA_DIR, filename)
        print(f"📡 Processing {filename} (Class {label})...")
        raw_data = parse_all_subcarriers(full_path)
        
        if raw_data is not None:
            clean_data = apply_dsp_pipeline(raw_data)
            feats, lbls = extract_features(clean_data, label)
            all_features.extend(feats)
            all_labels.extend(lbls)

    X = np.array(all_features)
    y = np.array(all_labels)

    if len(X) == 0:
        print("❌ CRITICAL ERROR: No data extracted. Did you run csi_logger.py first?")
        exit()

    print(f"\n📊 Total Datapoints Extracted: {len(X)}")
    
    # 2. Train/Test Split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    # 3. Train the Random Forest (With Anti-Overfitting applied)
    print("🧠 Training Random Forest Classifier...")
    clf = RandomForestClassifier(
        n_estimators=100, 
        max_depth=5,              # Forces generalization
        min_samples_leaf=10,      # Prevents memorizing micro-movements
        class_weight="balanced",  
        random_state=42
    )
    clf.fit(X_train, y_train)

    # Save the model in the main wifi_localization folder
    joblib.dump(clf, "prism_model.pkl")
    print("💾 Model saved locally as 'prism_model.pkl'")

    # 4. Evaluate the AI
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    
    print("\n=========================================")
    print(f"🎯 PRISM AI GENERALIZED ACCURACY: {accuracy * 100:.2f}%")
    print("=========================================\n")
    
    print("🔍 Confusion Matrix:")
    cm = confusion_matrix(y_test, y_pred)
    df_cm = pd.DataFrame(cm, index=[f"Act {n}" for n in class_names], columns=[f"Pred {n}" for n in class_names])
    print(df_cm.to_string())
    print("\n=========================================")